### ISSUE TITLE
view_cube import error

### ISSUE THREAD

**Issue by 861** [spectralpython/spectral#45] opened 2016-04-14 14:18 UTC
I have installed wxPython on my win10 x64 correctly ,but when I    use  spectral.view_cube(img, bands=[0, 1, 2])

Traceback (most recent call last):
  File "N:\new.py", line 7, in <module>
    spectral.view_cube(img, bands=[0, 1, 2])
  File "C:\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\spectral\graphics\graphics.py", line 178, in view_cube
    from spectral.graphics.hypercube import HypercubeWindow
  File "C:\WinPython-32bit-2.7.10.2\python-2.7.10\lib\site-packages\spectral\graphics\hypercube.py", line 73, in <module>
    raise ImportError("Required dependency wx.glcanvas not present")
ImportError: Required dependency wx.glcanvas not present

**Comment by tboggs** [comment] 2016-04-14 14:29
As the exception indicates, it was not possible to import the `glcanvas` submodule from the `wx` package. Is it possible that you don't have PyOpenGL installed? Take a look [here](http://wiki.wxpython.org/GLCanvas) for more info.

**Comment by 861** [comment] 2016-04-14 14:47
I have also installed pyopengl on my pc

**Comment by tboggs** [comment] 2016-04-14 19:42
Please try running the example app at the link in my previous message and let me know the result.

**Comment by tboggs** [comment] 2016-04-14 20:02
Actually, you may want to try this example for more informative output:

[http://wiki.wxpython.org/GLCanvas%20update](http://wiki.wxpython.org/GLCanvas%20update)

**Comment by 861** [comment] 2016-04-15 00:55
I can run the demo correctly as follow:
![image](https://cloud.githubusercontent.com/assets/7991297/14548254/b6cbbbcc-02e7-11e6-8c94-c660df676d95.png)
![image](https://cloud.githubusercontent.com/assets/7991297/14548256/be60a8c0-02e7-11e6-8cbf-eb84203e9a9f.png)
![image](https://cloud.githubusercontent.com/assets/7991297/14548258/c27dbe3e-02e7-11e6-8341-04d0563f0961.png)

**Comment by tboggs** [comment] 2016-04-15 01:14
Interesting. Please try the following:

Open a new python session and type:

```
>>> from wx import glcanvas
```

Then, exit python, open a new python session, and type:

```
>>> import wx
>>> from wx import glcanvas
```

Do both of those tests work for you without errors?

**Comment by 861** [comment] 2016-04-15 01:17
![image](https://cloud.githubusercontent.com/assets/7991297/14548592/bb282ac2-02ea-11e6-9bb0-f55f3ad85f20.png)
![image](https://cloud.githubusercontent.com/assets/7991297/14548601/d8843aa2-02ea-11e6-8ac2-bfe0532be0e2.png)

**Comment by tboggs** [comment] 2016-04-15 12:39
Ok. A few more things to clarify..

When you call `view_cube`, are you using ipython or the standard python interpreter?

When you call `view_cube`, are you doing it from an interactive ipython session?

Lastly, I notice you are using a script called "new.py". That is potentially dangerous because there is a standard python module named "new" and you could be masking it (see [here](http://stackoverflow.com/questions/29644219/import-error-in-python)). Please try renaming that file and see if the error goes away.

**Comment by 861** [comment] 2016-04-16 09:23
Thanks for your help！I just try it again！I can use the ipython run it correctly!But there is something wrong with the  standard python interpreter！

**Comment by tboggs** [comment] 2016-04-16 12:53
For the interactive graphical functions of SPy to work, the ipython interpreter is required. But I'm still surprised by the import exception you received. Did changing the file name eliminate that error?

**Comment by 861** [comment] 2016-04-17 00:33
I have changed my file name ,But the exception is still exist

**Comment by 861** [comment] 2016-04-17 00:38
I also have another problem about the test!

------------------------------------------------------------------------
Running memmap tests.
------------------------------------------------------------------------
Testing memmaps with BIL image file.
Saving C:\Users\Hmily\spectral\spectral_test_files\memmap_test_bil.img
Testing bil_memmap_read..................................... Traceback (most recent call last):
  File "C:\WinPython-32bit-2.7.10.2\python-2.7.10\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\WinPython-32bit-2.7.10.2\python-2.7.10\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Hmily\spectral\spectral\tests\run.py", line 68, in <module>
    test.run()
  File "spectral\tests\memmap.py", line 192, in run
    suite.run()
  File "spectral\tests\memmap.py", line 186, in run
    test.run()
  File "spectral\tests\spytest.py", line 76, in run
    method()
  File "spectral\tests\memmap.py", line 108, in test_bil_memmap_read
    self.create_test_image_file()
  File "spectral\tests\memmap.py", line 95, in create_test_image_file
    force=True)
  File "spectral\io\envi.py", line 455, in save_image
    _write_image(hdr_file, data, metadata, **kwargs)
  File "spectral\io\envi.py", line 687, in _write_image
    fout = builtins.open(img_file, 'wb', bufsize)
IOError: [Errno 22] invalid mode ('wb') or filename: u'C:\\Users\\Hmily\\spectral\\spectral_test_files\\memmap_test_bil.img'

**Comment by 861** [comment] 2016-04-17 00:39
![image](https://cloud.githubusercontent.com/assets/7991297/14584406/e8174d54-0477-11e6-8509-36df1c5954bf.png)

**Comment by tboggs** [comment] 2016-04-18 13:56
I can't explain your unit test error or why it would be related to the SPy module. The error is associated with a basic file-open operation. To figure out what is going on, you could create the directory (`C:\Users\Hmily\spectral\spectral_test_files`) manually and try running the same command from the python command line to see if that works:

    >>> open(u'C:\\Users\\Hmily\\spectral\\spectral_test_files\\memmap_test_bil.img', 'wb', 100)

If that works, I would retry running the SPy unit tests from a different directory (not from within the `spectral` directory) and see if it works from there. If you still get the error, please report what versions of windows and python you are using.

**Comment by 861** [comment] 2016-04-18 14:23
I have tried the command：`open(u'C:\\Users\\Hmily\\spectral\\spectral_test_files\\memmap_test_bil.img', 'wb', 100)`
It worked！But when I retry unit tests in a different directory ,the error is still exist on win10 x64 ,python 2.7.10.I will try it on Ubuntu  tomorrow.Thank you very much!

**Comment by tboggs** [comment] 2016-04-26 17:45
I'm closing this issue since the original problem was due to not running ipython. If the unit test error can be reproduced on another system (Windows or other), we'll create a separate issue.

**Closed by tboggs** 2016-04-26 17:45 UTC
